version: "3.8"

services:
  moviesApp:
    image: movies-app:latest
    container_name: movies-app
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=postgres
      - MYSQL_PORT=5432
    healthcheck:
      test: "curl http://localhost:8080/actuator/health"
      start_period: 40s
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:10.5
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moviesdb
    ports:
      - '5432:5432'