version: "3.8"

services:
  moviesApp:
    image: movies-app:latest
    container_name: movies-app
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
    links:
      - mysql
    networks:
      - backend
    healthcheck:
      test: "curl http://localhost:8080/actuator/health"
      start_period: 40s
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.25
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=moviesdb
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 30s
    networks:
      - backend

networks:
  backend:
    driver: "bridge"