apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.5
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: moviesdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
#          volumeMounts:
#            - mountPath: "/var/lib/postgresql/data"
#              name: "mendix-pgdata"
#      volumes:
#        - hostPath:
#            path: "/home/docker/pgdata"
#          name: mendix-pgdata

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres