apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        metrics_path: /actuator/prometheus
        scheme: http

        static_configs:
        - targets: ['172.20.234.113:31206']