apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    prometheus: prometheus-kube-prometheus-prometheus
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9090
  selector:
    prometheus: prometheus-kube-prometheus-prometheus

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app.kubernetes.io/name: grafana

---

apiVersion: v1
kind: Service
metadata:
  name: alert-managaer
  labels:
    app.kubernetes.io/name: alertmanager
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9093
  selector:
    app.kubernetes.io/name: alertmanager